// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'breadcrumbItem': string;
  'btnSave': string;
  'commandBarItems': string;
  'commandBarSeparators': string;
  'formBoilerplate': string;
  'helloForm': string;
}
const cssExports: CssExports;
export default cssExports;
